import {
  UtensilsCrossed,
  Coffee,
  Croissant,
  Scissors,
  BookOpen,
  Dumbbell,
  Flower2,
  Sparkles,
  PawPrint,
  Wrench,
  Store,
  Beer,
  ShoppingBag,
  Hammer,
  Briefcase,
  Stethoscope,
  GraduationCap,
  Palette,
  PartyPopper,
  Hotel,
  Building2,
  Laptop,
  HeartHandshake,
  type LucideProps,
} from 'lucide-react'

const icons = {
  UtensilsCrossed,
  Coffee,
  Croissant,
  Scissors,
  BookOpen,
  Dumbbell,
  Flower2,
  Sparkles,
  PawPrint,
  Wrench,
  Store,
  Beer,
  ShoppingBag,
  Hammer,
  Briefcase,
  Stethoscope,
  GraduationCap,
  Palette,
  PartyPopper,
  Hotel,
  Building2,
  Laptop,
  HeartHandshake,
} as const

export function CategoryIcon({ name, ...props }: { name: string } & LucideProps) {
  const Icon = icons[name as keyof typeof icons] ?? Store
  return <Icon {...props} />
}
