import type { Business, Category, City, DayHours, Review } from './types'

export const categories: Category[] = [
  { id: 'restaurants', name: 'Restaurants', icon: 'UtensilsCrossed' },
  { id: 'cafe', name: 'Cafés', icon: 'Coffee' },
  { id: 'bakery', name: 'Bakeries', icon: 'Croissant' },
  { id: 'salon', name: 'Salons', icon: 'Scissors' },
  { id: 'bookstore', name: 'Bookstores', icon: 'BookOpen' },
  { id: 'gym', name: 'Fitness', icon: 'Dumbbell' },
  { id: 'florist', name: 'Florists', icon: 'Flower2' },
  { id: 'yoga', name: 'Yoga & Wellness', icon: 'Sparkles' },
  { id: 'petstore', name: 'Pet Stores', icon: 'PawPrint' },
  { id: 'autoshop', name: 'Auto Repair', icon: 'Wrench' },
]

export const cities: City[] = [
  { id: 'riverton', name: 'Riverton', lat: 40.0, lng: -74.0 },
  { id: 'oakdale', name: 'Oakdale', lat: 40.1, lng: -74.1 },
  { id: 'brookside', name: 'Brookside', lat: 39.9, lng: -73.9 },
]

const categoryImage: Record<string, string> = {
  restaurants: '/businesses/restaurant.png',
  cafe: '/businesses/cafe.png',
  bakery: '/businesses/bakery.png',
  salon: '/businesses/salon.png',
  bookstore: '/businesses/bookstore.png',
  gym: '/businesses/gym.png',
  florist: '/businesses/florist.png',
  yoga: '/businesses/yoga.png',
  petstore: '/businesses/petstore.png',
  autoshop: '/businesses/autoshop.png',
}

// hours helpers (minutes from midnight)
const h = (hour: number, min = 0) => hour * 60 + min
const std = (open: number, close: number): DayHours => ({ open, close })
const closed: DayHours = { open: null, close: null }

const weekday = (open: number, close: number, weekend?: { open: number; close: number }) => ({
  mon: std(open, close),
  tue: std(open, close),
  wed: std(open, close),
  thu: std(open, close),
  fri: std(open, close),
  sat: weekend ? std(weekend.open, weekend.close) : std(open, close),
  sun: weekend ? std(weekend.open, weekend.close) : closed,
})

export const businesses: Business[] = [
  {
    id: 'the-copper-fork',
    name: 'The Copper Fork',
    categoryId: 'restaurants',
    tagline: 'Seasonal farm-to-table plates',
    description:
      'A cozy neighborhood bistro serving seasonal, locally-sourced dishes in a warm, candle-lit room. Our menu changes weekly based on what local farms bring to our door.',
    image: categoryImage.restaurants,
    city: 'riverton',
    address: '128 Maple Avenue, Riverton',
    lat: 40.005,
    lng: -74.008,
    phone: '(555) 214-8890',
    email: 'hello@copperfork.example',
    website: 'copperfork.example',
    priceLevel: 3,
    featured: true,
    keywords: ['copper fork', 'coper fork', 'bistro', 'dinner', 'farm to table', 'american'],
    hours: weekday(h(11), h(22), { open: h(10), close: h(23) }),
  },
  {
    id: 'nonna-lucias',
    name: "Nonna Lucia's Trattoria",
    categoryId: 'restaurants',
    tagline: 'Handmade pasta & wood-fired pizza',
    description:
      'Family-run Italian trattoria pouring generations of recipes into every plate. Fresh pasta made daily and a wood-fired oven going all evening.',
    image: categoryImage.restaurants,
    city: 'oakdale',
    address: '44 Bridge Street, Oakdale',
    lat: 40.104,
    lng: -74.093,
    phone: '(555) 771-2093',
    email: 'ciao@nonnalucia.example',
    website: 'nonnalucia.example',
    priceLevel: 2,
    featured: false,
    keywords: ['nonna lucia', 'nona lucia', 'italian', 'pasta', 'pizza', 'trattoria'],
    hours: weekday(h(16), h(23)),
  },
  {
    id: 'daybreak-coffee',
    name: 'Daybreak Coffee Roasters',
    categoryId: 'cafe',
    tagline: 'Small-batch roasts & warm pastries',
    description:
      'Specialty coffee roasted in-house every morning. Pull up a chair, grab a flat white, and stay a while — free wifi and plenty of plugs.',
    image: categoryImage.cafe,
    city: 'riverton',
    address: '9 Sunrise Lane, Riverton',
    lat: 39.997,
    lng: -74.004,
    phone: '(555) 330-1188',
    email: 'brew@daybreak.example',
    website: 'daybreakcoffee.example',
    priceLevel: 1,
    featured: true,
    keywords: ['daybreak', 'day break', 'coffee', 'espresso', 'latte', 'roasters', 'cafe'],
    hours: weekday(h(6, 30), h(18), { open: h(7), close: h(19) }),
  },
  {
    id: 'the-third-cup',
    name: 'The Third Cup',
    categoryId: 'cafe',
    tagline: 'Neighborhood espresso bar',
    description:
      'A tiny corner espresso bar with big personality. Known for our cardamom latte and rotating local art on the walls.',
    image: categoryImage.cafe,
    city: 'brookside',
    address: '212 Elm Court, Brookside',
    lat: 39.905,
    lng: -73.907,
    phone: '(555) 908-4412',
    email: 'hi@thirdcup.example',
    website: 'thirdcup.example',
    priceLevel: 1,
    featured: false,
    keywords: ['third cup', '3rd cup', 'coffee', 'espresso', 'cafe'],
    hours: weekday(h(7), h(17)),
  },
  {
    id: 'flour-and-honey',
    name: 'Flour & Honey Bakery',
    categoryId: 'bakery',
    tagline: 'Sourdough, croissants & celebration cakes',
    description:
      'Artisan bakery crafting naturally-leavened breads and buttery pastries. Order custom cakes for any occasion with a week of notice.',
    image: categoryImage.bakery,
    city: 'riverton',
    address: '76 Willow Road, Riverton',
    lat: 40.011,
    lng: -73.995,
    phone: '(555) 442-7781',
    email: 'orders@flourandhoney.example',
    website: 'flourandhoney.example',
    priceLevel: 2,
    featured: true,
    keywords: ['flour and honey', 'flour honey', 'bakery', 'bread', 'cake', 'croissant', 'pastry'],
    hours: weekday(h(7), h(16), { open: h(8), close: h(14) }),
  },
  {
    id: 'the-mane-room',
    name: 'The Mane Room',
    categoryId: 'salon',
    tagline: 'Modern cuts & color',
    description:
      'A relaxed, inclusive salon focused on healthy hair and precision cuts. Book online or walk in for a fringe trim.',
    image: categoryImage.salon,
    city: 'oakdale',
    address: '18 Cedar Plaza, Oakdale',
    lat: 40.096,
    lng: -74.105,
    phone: '(555) 655-3320',
    email: 'book@maneroom.example',
    website: 'maneroom.example',
    priceLevel: 2,
    featured: false,
    keywords: ['mane room', 'main room', 'salon', 'hair', 'haircut', 'barber', 'color'],
    hours: weekday(h(9), h(19), { open: h(9), close: h(17) }),
  },
  {
    id: 'chapter-and-verse',
    name: 'Chapter & Verse Books',
    categoryId: 'bookstore',
    tagline: 'Independent bookshop & reading nook',
    description:
      'Lovingly curated fiction, poetry, and local authors. Cozy reading corners, weekly book clubs, and staff picks you can trust.',
    image: categoryImage.bookstore,
    city: 'brookside',
    address: '5 Harbor Street, Brookside',
    lat: 39.894,
    lng: -73.902,
    phone: '(555) 120-6647',
    email: 'read@chapterverse.example',
    website: 'chapterverse.example',
    priceLevel: 2,
    featured: true,
    keywords: ['chapter and verse', 'chapter verse', 'books', 'bookstore', 'bookshop', 'reading'],
    hours: weekday(h(10), h(20), { open: h(10), close: h(18) }),
  },
  {
    id: 'ironworks-fitness',
    name: 'Ironworks Fitness Co.',
    categoryId: 'gym',
    tagline: 'Strength training & group classes',
    description:
      'A community-first gym with expert coaches, free weights, and daily group classes. First class is always on us.',
    image: categoryImage.gym,
    city: 'riverton',
    address: '301 Foundry Way, Riverton',
    lat: 40.002,
    lng: -74.015,
    phone: '(555) 877-9002',
    email: 'train@ironworks.example',
    website: 'ironworksfitness.example',
    priceLevel: 2,
    featured: false,
    keywords: ['ironworks', 'iron works', 'gym', 'fitness', 'workout', 'training', 'weights'],
    hours: weekday(h(5), h(23), { open: h(7), close: h(20) }),
  },
  {
    id: 'petals-and-stems',
    name: 'Petals & Stems',
    categoryId: 'florist',
    tagline: 'Fresh arrangements & event florals',
    description:
      'Seasonal blooms arranged with care for birthdays, weddings, and just-because moments. Same-day local delivery available.',
    image: categoryImage.florist,
    city: 'oakdale',
    address: '62 Garden Terrace, Oakdale',
    lat: 40.108,
    lng: -74.096,
    phone: '(555) 233-7710',
    email: 'bloom@petalsstems.example',
    website: 'petalsandstems.example',
    priceLevel: 2,
    featured: true,
    keywords: ['petals and stems', 'petals stems', 'florist', 'flowers', 'bouquet', 'arrangement'],
    hours: weekday(h(9), h(18), { open: h(9), close: h(15) }),
  },
  {
    id: 'still-point-yoga',
    name: 'Still Point Yoga Studio',
    categoryId: 'yoga',
    tagline: 'Vinyasa, restorative & meditation',
    description:
      'A calm, sunlit studio offering classes for every body and every level. Drop in or join a membership — mats provided.',
    image: categoryImage.yoga,
    city: 'brookside',
    address: '140 Serenity Ave, Brookside',
    lat: 39.902,
    lng: -73.896,
    phone: '(555) 559-0043',
    email: 'namaste@stillpoint.example',
    website: 'stillpointyoga.example',
    priceLevel: 2,
    featured: false,
    keywords: ['still point', 'stillpoint', 'yoga', 'meditation', 'wellness', 'vinyasa'],
    hours: weekday(h(6), h(21), { open: h(8), close: h(18) }),
  },
  {
    id: 'happy-tails',
    name: 'Happy Tails Pet Supply',
    categoryId: 'petstore',
    tagline: 'Everything for your best friend',
    description:
      'Locally-owned pet shop stocking premium food, toys, and gear. Ask about our loyalty program and free nail trims on Sundays.',
    image: categoryImage.petstore,
    city: 'riverton',
    address: '88 Barkley Blvd, Riverton',
    lat: 40.008,
    lng: -74.001,
    phone: '(555) 646-1120',
    email: 'woof@happytails.example',
    website: 'happytailspets.example',
    priceLevel: 1,
    featured: false,
    keywords: ['happy tails', 'happytails', 'pet', 'pets', 'dog', 'cat', 'pet store', 'supplies'],
    hours: weekday(h(9), h(20), { open: h(10), close: h(18) }),
  },
  {
    id: 'redline-auto',
    name: 'Redline Auto Care',
    categoryId: 'autoshop',
    tagline: 'Honest repairs & fast service',
    description:
      'Full-service auto repair with certified mechanics and upfront pricing. Free multi-point inspection with every oil change.',
    image: categoryImage.autoshop,
    city: 'oakdale',
    address: '410 Motorway Drive, Oakdale',
    lat: 40.112,
    lng: -74.088,
    phone: '(555) 900-5521',
    email: 'service@redlineauto.example',
    website: 'redlineauto.example',
    priceLevel: 2,
    featured: false,
    keywords: ['redline', 'red line', 'auto', 'car', 'mechanic', 'repair', 'oil change', 'tires'],
    hours: weekday(h(8), h(18), { open: h(9), close: h(14) }),
  },
  {
    id: 'the-green-plate',
    name: 'The Green Plate',
    categoryId: 'restaurants',
    tagline: 'Plant-forward comfort food',
    description:
      'Bright, veggie-loved cooking that even the carnivores rave about. Bowls, burgers, and killer weekend brunch.',
    image: categoryImage.restaurants,
    city: 'brookside',
    address: '27 Park Row, Brookside',
    lat: 39.897,
    lng: -73.905,
    phone: '(555) 318-2255',
    email: 'eat@greenplate.example',
    website: 'thegreenplate.example',
    priceLevel: 2,
    featured: false,
    keywords: ['green plate', 'vegetarian', 'vegan', 'brunch', 'healthy', 'restaurant'],
    hours: weekday(h(10), h(21), { open: h(9), close: h(22) }),
  },
  {
    id: 'morning-glory-cafe',
    name: 'Morning Glory Café',
    categoryId: 'cafe',
    tagline: 'All-day breakfast & good coffee',
    description:
      'A sunny all-day café known for fluffy pancakes, loaded avocado toast, and bottomless drip coffee.',
    image: categoryImage.cafe,
    city: 'oakdale',
    address: '33 Meadow Lane, Oakdale',
    lat: 40.099,
    lng: -74.101,
    phone: '(555) 774-6689',
    email: 'hello@morningglory.example',
    website: 'morningglorycafe.example',
    priceLevel: 1,
    featured: false,
    keywords: ['morning glory', 'breakfast', 'brunch', 'coffee', 'cafe', 'pancakes'],
    hours: weekday(h(7), h(15)),
  },
  {
    id: 'sweet-crumb',
    name: 'Sweet Crumb Patisserie',
    categoryId: 'bakery',
    tagline: 'French pastries & macarons',
    description:
      'Delicate French patisserie handcrafting éclairs, tarts, and a rainbow of macarons daily. Perfect for gifting.',
    image: categoryImage.bakery,
    city: 'brookside',
    address: '11 Rue Court, Brookside',
    lat: 39.909,
    lng: -73.898,
    phone: '(555) 221-4478',
    email: 'bonjour@sweetcrumb.example',
    website: 'sweetcrumb.example',
    priceLevel: 3,
    featured: false,
    keywords: ['sweet crumb', 'patisserie', 'french', 'macaron', 'pastry', 'bakery', 'dessert'],
    hours: weekday(h(8), h(18), { open: h(9), close: h(16) }),
  },
  {
    id: 'clip-and-co',
    name: 'Clip & Co Barbershop',
    categoryId: 'salon',
    tagline: 'Classic cuts & hot-towel shaves',
    description:
      'A modern barbershop with old-school hospitality. Sharp fades, beard trims, and a complimentary drink while you wait.',
    image: categoryImage.salon,
    city: 'riverton',
    address: '52 Grand Street, Riverton',
    lat: 40.003,
    lng: -73.998,
    phone: '(555) 664-9931',
    email: 'book@clipandco.example',
    website: 'clipandco.example',
    priceLevel: 2,
    featured: false,
    keywords: ['clip and co', 'clip co', 'barber', 'barbershop', 'haircut', 'shave', 'salon'],
    hours: weekday(h(9), h(19), { open: h(9), close: h(18) }),
  },
  {
    id: 'trailhead-outfitters',
    name: 'Trailhead Outfitters',
    categoryId: 'petstore',
    tagline: 'Gear for dogs who love the outdoors',
    description:
      'Specialty pet outfitter for active dogs — durable harnesses, cooling gear, and trail treats. Dogs always welcome inside.',
    image: categoryImage.petstore,
    city: 'brookside',
    address: '3 Summit Way, Brookside',
    lat: 39.9,
    lng: -73.91,
    phone: '(555) 445-7789',
    email: 'hey@trailheadpets.example',
    website: 'trailheadoutfitters.example',
    priceLevel: 2,
    featured: false,
    keywords: ['trailhead', 'trail head', 'pet', 'dog', 'outdoor', 'gear', 'harness'],
    hours: weekday(h(10), h(19), { open: h(10), close: h(17) }),
  },
  {
    id: 'lotus-and-lantern',
    name: 'Lotus & Lantern Wellness',
    categoryId: 'yoga',
    tagline: 'Yoga, sound baths & massage',
    description:
      'A holistic wellness haven blending movement, breathwork, and bodywork. Book a class or a restorative massage.',
    image: categoryImage.yoga,
    city: 'oakdale',
    address: '90 Lantern Lane, Oakdale',
    lat: 40.106,
    lng: -74.099,
    phone: '(555) 552-8834',
    email: 'peace@lotuslantern.example',
    website: 'lotusandlantern.example',
    priceLevel: 3,
    featured: false,
    keywords: ['lotus and lantern', 'lotus lantern', 'yoga', 'massage', 'wellness', 'sound bath', 'spa'],
    hours: weekday(h(7), h(21), { open: h(8), close: h(19) }),
  },
]

export const seedReviews: Review[] = [
  { id: 'r1', businessId: 'the-copper-fork', author: 'Maya R.', rating: 5, date: '2025-05-12', text: 'Absolutely stunning seasonal menu. The mushroom risotto changed my life.' },
  { id: 'r2', businessId: 'the-copper-fork', author: 'Devon P.', rating: 4, date: '2025-04-28', text: 'Great food and atmosphere, a touch pricey but worth it for a special night.' },
  { id: 'r3', businessId: 'the-copper-fork', author: 'Aisha K.', rating: 5, date: '2025-06-01', text: 'Best date-night spot in Riverton. The staff remembered our anniversary!' },
  { id: 'r4', businessId: 'daybreak-coffee', author: 'Tom H.', rating: 5, date: '2025-05-30', text: 'The flat white is perfect and the pastries sell out fast for good reason.' },
  { id: 'r5', businessId: 'daybreak-coffee', author: 'Lena M.', rating: 4, date: '2025-05-18', text: 'My go-to remote work spot. Fast wifi, friendly baristas, great vibe.' },
  { id: 'r6', businessId: 'flour-and-honey', author: 'Carlos G.', rating: 5, date: '2025-06-03', text: 'Ordered a birthday cake and it was gorgeous AND delicious. Highly recommend.' },
  { id: 'r7', businessId: 'chapter-and-verse', author: 'Priya S.', rating: 5, date: '2025-05-22', text: 'The staff picks are always spot on. I never leave empty-handed.' },
  { id: 'r8', businessId: 'petals-and-stems', author: 'Jordan T.', rating: 5, date: '2025-05-09', text: 'Same-day delivery saved me on my mom\u2019s birthday. Beautiful bouquet.' },
  { id: 'r9', businessId: 'nonna-lucias', author: 'Rachel B.', rating: 4, date: '2025-04-15', text: 'Fresh pasta was incredible. Gets busy on weekends so book ahead.' },
  { id: 'r10', businessId: 'ironworks-fitness', author: 'Sam D.', rating: 5, date: '2025-05-27', text: 'Coaches actually care about your form. Best gym community around.' },
  { id: 'r11', businessId: 'still-point-yoga', author: 'Nina F.', rating: 5, date: '2025-06-02', text: 'Left every class feeling lighter. The restorative sessions are magic.' },
  { id: 'r12', businessId: 'redline-auto', author: 'Marcus L.', rating: 4, date: '2025-05-11', text: 'Honest pricing and they explained everything. Rare to find these days.' },
  { id: 'r13', businessId: 'the-third-cup', author: 'Ellie W.', rating: 5, date: '2025-05-19', text: 'That cardamom latte lives in my head rent free. Tiny but mighty.' },
  { id: 'r14', businessId: 'happy-tails', author: 'Greg N.', rating: 5, date: '2025-05-25', text: 'Free Sunday nail trims and the staff know my pup by name. Love this place.' },
  { id: 'r15', businessId: 'sweet-crumb', author: 'Bianca V.', rating: 5, date: '2025-06-04', text: 'The macarons are the best I have had outside of Paris. No notes.' },
  { id: 'r16', businessId: 'the-green-plate', author: 'Owen R.', rating: 4, date: '2025-05-14', text: 'Weekend brunch is a must. The vegan burger converted my skeptic friend.' },
]
